apiVersion: v1
kind: Service
metadata:
  name: sup-svc
spec:
  selector:
    app: super
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sup-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: super
  template:
    metadata:
      labels:
        app: super
    spec:
      containers:
        - name: super
          image: leekyeongseo/supermario:13
